language: go
sudo: false
go:
  - tip

before_script:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-cache search gfortran
        sudo apt-get install -f -y --force-yes gfortran
      fi

script:
  - go test -covermode=count  -coverprofile=coverage.out ./...

after_success:
  - include_cov=coverage.out bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt
