language: go

go:
  - "1.8"

os:
  - linux

before_script:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get update
        sudo apt-cache search clang
        sudo apt-get install -f -y --force-yes gfortran
      fi

  # gocovmerge is used to merge all the separate unit/integration test coverage
  # profiles.
  - go get -u -v github.com/wadey/gocovmerge

script:
  - . ./travis.sh

after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt
