# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

# Only the last two Go releases are supported by the Go team with security
# updates. Any older versions be considered deprecated. Don't bother testing
# with them.
go:
  - 1.9.x
  - 1.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
- sudo apt-get install gfortran
  # gocovmerge is used to merge all the separate unit/integration test coverage
  # profiles.
  - go get -u -v github.com/wadey/gocovmerge

script:
  - . ./travis.sh
  - echo "" > coverage.txt
  - go test -v -race ./...  # Run all the tests with the race detector enabled


after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)
