         3      $ IPRINT = control (1 or 2 or 3) for list output
         3      $ IPLOT  = control (0 or 1 or 2 or 3) for plot output
         0      $ NLAST = plot options  (-1=none, 0=geometry, 1=u,v,w)
      Y         $ Do you want to plot the discretized model?
      N         $ Are there any regions for which you want expanded plots?
         1      $ NSTEPS = quantity of time steps for list or plot output
         2      $ LSTEP(i)= output is desired for time step no.
       350      $ TIME(i) = time corresponding to LSTEP( 1)
         1      $ IFLAG = control (0 or 1) for amount of prebuckling output
  0.5000000     $ FMAX = normalization factor for plotting deformed shell
      Y         $ Do you want prebuckling output for all the segments?
         1      $ NMODES=quantity of buckling modes to be listed, plotted
         1      $ NTHMOD(i)=ith mode calculated in last main run. i=( 1)
         6      $ NWAVE(i)=no. of circ. waves in the ith mode. i=( 1)
      Y         $ Do you want buckling modal output for all the segments?
