
11 February, 2002, revised December 19, 2008

             INFORMATION ABOUT UPDATING PANDA2, BOSOR4, etc.
             ARCHIVING THE UPDATED PANDA2, BOSOR4, etc, PRODUCING
             COMPRESSED "TAR" FILE OF THE ARCHIVE,
             ftp-ing THE "TAR" FILE TO A CUSTOMER,
             RECONSTRUCTING THE PANDA2, BOSOR4, etc, DIRECTORY STRUCTURE,
             AND INITIALIZING IN PREPARATION FOR RUNS.

   (NOTE: This file was originally written with PANDA2 in mind. Therefore
          most of the examples involve PANDA2. However, the same
          instructions apply to BOSOR4, BOSOR5, and other programs by
          Bushnell).
=======================================================================

(See the file ..doc/howto.update for more details with regard to
 PARTS I - V and PARTs VIII, IX)
========================================================================

PART VI
HOW TO RESTRUCTURE DIRECTORIES AT THE USER'S FACILITY (INSTALL)

1. Go to the directory which you want to be the PARENT of that
   where you want PANDA2, BOSOR4, BOSOR5, etc. to reside. If you
   have a tape, copy the file panda2.<machine>.tar.Z from the tape
   to a file with the same name. This is a compressed tar file.
   The argument <machine> of the file name stands for the platform
   (sun4, sgi, dec, hp700, rs6k, etc).

-----------------------------------------------------------------------
   How to read tape:
   (a) go to directory where you want the compressed tar file to reside,
       usually, this will be the PARENT of that where you want PANDA2,
       BOSOR4, etc. to reside.
   (b) insert the tape in the tape drive.
   (c) type ONE of the commands listed next:
        tar xf /dev/mt/tps1d5.8500  (tps1d5.8500 is name used at lockheed)
        tar xv                      (used for default drive)
-----------------------------------------------------------------------

2. With a *.tar.Z file (that is, a compressed tar file transferred
   via ftp or copied from a tape:
        uncompress *.tar.Z   (for example: uncompress panda2.sgi.tar.Z)
        tar xvf    *.tar     (for example: tar xvf    panda2.sgi.tar)
   With a *.tar file, just type
        tar xvf *.tar        (for example: tar xvf bigb4b4p2.linux.tar)

   For example, if you have the following "tar" file:
-rw-r--r--   1 bush     bosor    583339520 Mar 20  2009 bigb4b4b5p2g.linuxhp700.tar
   which contains bigbosor4, bosor4, bosor5, panda2, and genopt for operation
   on either a LINUX machine or on a UNIX machine (Hewlett-Packard hp700)
   after you type:
      tar xvf bigb4b4b5p2g.linuxhp700.tar
   you should have the following directory structure:

-rw-r--r--   1 bush     bosor    583339520 Mar 20  2009 bigb4b4b5p2g.linuxhp700.tar
drwxr-xr-x  11 bush     bosor        512 Mar 18 05:44 bigbosor4/
drwxr-xr-x   2 bush     bosor        512 Mar 18 05:44 bin/
drwxr-xr-x  11 bush     bosor        512 Mar 18 05:45 bosor4/
drwxr-xr-x  11 bush     bosor        512 Mar 18 05:45 bosor5/
drwxr-xr-x   9 bush     bosor       1536 Jun 15  1997 gawk/
drwxr-xr-x  11 bush     bosor        512 Mar 18 05:46 genopt/
-rw-r-----   1 bush     bosor       4035 Dec  4  2006 install
drwxr-xr-x  11 bush     bosor        512 Mar 18 05:46 panda2/
drwxr-xr-x   2 bush     bosor       1024 Mar 18 05:44 plotps/
drwxr-xr-x   2 bush     bosor       3072 Mar 18 05:44 util/
drwxr-xr-x   4 bush     bosor       1536 Oct  7  1993 xgraph/


3. Check to make sure that you have the program "install" and that "install"
   is executable.  If it is not, then give the command "chmod 700 install"

4. Execute "install":     install
   and follow the directions that appear at the end of the output
   NOTE: There are some systems that use the word "install" for special
   purposes. You may have to give the command (..path to PANDA2's version
   of install)/install
========================================================================

PART VII
HOW TO RUN

1. All users of BOSOR4, BOSOR5, PANDA2, GENOPT, etc. must run the shell
program called "initialize", which is located in the bin/ directory,
before running any of the programs. They must run "initialize" by 
"source-ing" the file so that the environment variables "initialize"
initializes exist in the user's top-level environment:

        source (..path to bin/...)/bin/initialize

Do "pwd" to find the path to bin/.

NOTE: There are two /bin directories, one in the parent directory to
/panda2 and one in the /panda2 directory. The "bin" that is wanted here
is the one in the parent directory to /panda2.

ANOTHER NOTE: If customer users are on ksh (korn shell) rather than
csh (C shell), then before "source" you must type

       /bin/csh

2. Before you start to run:
   a. go to the directory where you want to run a case.
   b. type the command:
      bigbosor4log  (if you plan to run BIGBOSOR4)
      panda2log     (if you plan to run PANDA2)
      genoptlog     (if you plan to run GENOPT
      bosor5log     (if you plan to run BOSOR5)

3. Follow the directions on your sceen and in the
   supporting literature.
==========================================================================
