         1      $ IPRINT = control (1 or 2 or 3) for list output
         1      $ IPLOT  = control (0 or 1 or 2 or 3) for plot output
         0      $ NLAST = plot options  (-1=none, 0=geometry, 1=u,v,w)
      y         $ Do you want to plot the discretized model?
      n         $ Are there any regions for which you want expanded plots?
         1      $ NSTEPS = quantity of time steps for list or plot output
         7      $ LSTEP(i)= output is desired for time step no.
   460.0000     $ TIME(i) = time corresponding to LSTEP( 1)
         1      $ IFLAG = control (0 or 1) for amount of prebuckling output
  0.3000000     $ FMAX = normalization factor for plotting deformed shell
      y         $ Do you want prebuckling output for all the segments?
